# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
#    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - aix_ppc64
      - android_arm64
      - darwin_amd64
      - darwin_arm64
      - dragonfly_amd64
      - freebsd_386
      - freebsd_amd64
      - freebsd_arm
      - freebsd_arm64
      - illumos_amd64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
      - linux_mips
      - linux_mips64
      - linux_mips64le
      - linux_mipsle
      - linux_ppc64
      - linux_ppc64le
      - linux_riscv64
      - linux_s390x
      - netbsd_386
      - netbsd_amd64
      - netbsd_arm
      - netbsd_arm64
      - openbsd_386
      - openbsd_amd64
      - openbsd_arm
      - openbsd_arm64
      - plan9_386
      - plan9_amd64
      - plan9_arm
      - solaris_amd64
      - windows_386
      - windows_amd64
      - windows_arm
      - windows_arm64
    main: ./cmd/main
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  replace_existing_draft: true
#  footer: >-
#
#    ---
#
#    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

report_sizes: true
